routes/web.php
<?php

use App\Http\Controllers\RestaurantController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\BookingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [SearchController::class, 'index'])->name("home");
Route::view('/restaurant-sign-up', 'restaurant.sign_up')->name("restaurant-sign-up");
Route::view('/contact-us', 'contact-us')->name('contact');
Route::view('/about-us', 'about-us')->name('about-us');
Route::view('/about-pre-authorisation', 'about-pre-authorisation')->name('about-pre-auth');
Route::get('/restaurant/{restaurant}', [RestaurantController::class, 'redirectWithName']);
Route::get('/restaurant/{restaurant}/{name}', [RestaurantController::class, 'show'])->name("restaurant.show");
Route::get('/restaurant/email/verify/{restaurant}', [RestaurantController::class, 'verifyEmail'])->name("restaurant.verify_email");

Route::middleware(['auth:sanctum', 'verified', 'admin'])->group(function(){
    Route::get('restaurants/status/{status}', [RestaurantController::class, 'status'])->name('restaurant.status');
});

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::view('/bookings', 'bookings.index')->name("bookings");
    Route::view('/dashboard', 'dashboard')->name('dashboard');
    Route::view('/my-restaurants', 'restaurant.manage.index')->name("my-restaurants");
    Route::get('/my-restaurants/bookings', [RestaurantController::class, 'bookingsSelect'])->name("restaurant.bookings_select");
});

Route::middleware(['auth:sanctum', 'verified', 'booking'])->group(function(){
    Route::get('/bookings/{booking}', [BookingController::class, 'show'])->name("booking");
});

Route::middleware(['auth:sanctum', 'verified', 'restaurant'])->group(function(){
    Route::get('/restaurants/{restaurant}/bookings', [RestaurantController::class, 'bookings'])->name("restaurant.bookings");
    Route::get('/restaurants/{restaurant}/bookings/{booking}', [RestaurantController::class, 'booking'])->name("restaurant.booking");
    Route::get('/restaurants/{restaurant}/manage', [RestaurantController::class, 'manage'])->name("restaurant.manage");
    Route::get('/restaurant/email/verify/{restaurant}/resend', [RestaurantController::class, 'resendVerificationEmail'])->name("restaurant.verify_email.resend");
});

app/Models/Restaurant.php
<?php

namespace App\Models;

use App\Events\RestaurantCreated;
use App\Mail\Restaurant\EmailVerification;
use App\Traits\History;
use Carbon\Carbon;
use Carbon\CarbonInterval;
use Carbon\CarbonPeriod;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Laravel\Cashier\Billable;
use Spatie\Activitylog\Traits\LogsActivity;
use Stripe\Customer;
use Stripe\StripeClient;

class Restaurant extends Model
{
    use HasFactory, Billable, History;

    protected $fillable = [
        "name",
        "email",
        "phone",
        "address_line_1",
        "vicinity",
        "country",
        "postal_code",
        "lat",
        "lng",
    ];

    protected $dispatchesEvents = [
        'created' => RestaurantCreated::class,
    ];

    protected $dates = [
        "email_verified_at"
    ];

    protected $casts = [
        'open_hours' => 'array'
    ];

    public function __toString()
    {
        return $this->name;
    }

    // Relationships
    public function staff()
    {
        return $this->belongsToMany(User::class, 'restaurant_staff');
    }

    public function services()
    {
        return $this->hasMany(Service::class);
    }

    public function service_exceptions()
    {
        return $this->hasMany(ServiceException::class)->whereDate("service_date", ">=", Carbon::now());
    }

    public function open_hours_exceptions()
    {
        return $this->hasMany(OpenHoursException::class)->whereDate("open_date", ">=", Carbon::now());
    }

    public function tables()
    {
        return $this->hasMany(Table::class);
    }

    public function bookings()
    {
        return $this->hasMany(Booking::class);
    }

    public function booking_rules()
    {
        return $this->hasMany(BookingRule::class);
    }

    public function sections()
    {
        return $this->hasMany(RestaurantSection::class);
    }

    public function reviews()
    {
        return $this->hasManyThrough(Review::class, Booking::class);
    }

    public function invoiceItems()
    {
        return $this->hasMany(InvoiceItem::class);
    }

    public function tableBlocks()
    {
        return $this->hasMany(TableBlock::class)
            ->where("end_date", ">", Carbon::now());
    }

    // Accessors & Mutators
    public function getImageAttribute()
    {
        if(empty($this->image_location)){
            return $this->logo;
        }

        return Storage::url($this->image_location);
    }

    // Accessors & Mutators
    public function getLogoAttribute()
    {
        if(empty($this->logo_location)){
            return asset("/img/placeholder.jpg");
        }

        return Storage::url($this->logo_location);
    }

    public function getAddressAttribute()
    {
        $parts = ["address_line_1", "vicinity", "postal_code"];
        $address = [];

        foreach($parts as $part){
            if(!empty($this->$part)){
                $address[] = $this->$part;
            }
        }

        return implode(", ", $address);
    }

    public function getRateAttribute()
    {
        return 5;
    }

    public function getStatusAttribute($value)
    {
        $status = (object)[
            "icon" => $this->statusIcon($value),
            "text" => ucwords($value),
            "color" => ""
        ];

        switch(strtolower($value)){
            case "live":
                $status->color = "text-green-300";

                break;

            case "offline":
            case "rejected":
                $status->color = "text-red-600";

                break;

            default:
                $status->color = "text-yellow-300";

                break;
        }

        return $status;
    }

    public function getBookingTimeframeAttribute($value)
    {
        $parts = explode(":", $value);

        return [
            "covers" => $parts[0],
            "minutes" => $parts[1]
        ];
    }

    public function setBookingTimeframeAttribute($value)
    {
        $this->attributes['booking_timeframe'] = $value['covers'] . ":" . $value['minutes'];
    }

    public function getMonthlyPaymentAttribute()
    {
        return $this->tables()->where("bookable", 1)->count() * $this->rate;
    }

    public function getNextBillingDateAttribute()
    {
        $date = Carbon::parse(date("Y") . "-" . date("m") . "-" . $this->billing_date);

        while($date->isPast()){
            $date->addMonth();
        }

        return $date;
    }

    public function getNextPaymentAmountAttribute()
    {
        // get all outstanding invoice items
        $amount = $this->asStripeCustomer()->balance/100;

        $amount += $this->invoiceItems->sum("amount")/100;

        $amount += Carbon::now()->startOfDay()->diffInDays($this->next_billing_date) * $this->tables()->where("bookable", 1)->count() * $this->calculateDailyRate();

        return number_format($amount, 2);
    }

    // functions
    public function max_booking_size($section = "all")
    {
        if($section === "all"){
            $largestTable = $this->tables()
                ->where("bookable", 1)
                ->orderBy("seats", "DESC")
                ->first();
        } else {
            $largestTable = $this->tables()
                ->where("restaurant_section_id", $section)
                ->where("bookable", 1)
                ->orderBy("seats", "DESC")
                ->first();
        }

        if(!$largestTable){
            return 0;
        }

        return $largestTable->seats;
    }

    public function statusIcon($status)
    {
        $icons = [
            "live" => '<svg class="stroke-current h-full animate-pulse" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <circle cx="12" cy="12" r="6" fill="currentColor" />
                            </svg>',
            "offline" => '<svg class="stroke-current h-full" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>',
            "pending" => '<svg class="stroke-current h-full" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>',
            "rejected" => '<svg class="stroke-current h-full" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>',
        ];

        return $icons[$status];
    }

    public function myRestaurant()
    {
        return $this->staff()->where("user_id", Auth::user()->id)->first();
    }

    public function linkAccount()
    {

        return $this->createAsStripeCustomer([
            "name" => $this->name,
            "email" => $this->email,
            "phone" => $this->phone,
            "address" => [
                "line1" => $this->address_line_1,
                "city" => $this->vicinity,
                "postal_code" => $this->postal_code,
            ]
        ]);
    }

    public function servicesByDate(Carbon $date)
    {
        // check for exception services first
        $services = $this->service_exceptions()->whereDate("service_date", $date)->orderBy("start")->get();

        if($services->count()){
            $closed = $services->where("closed", 1);

            if($closed->count()){
                return collect([]);
            }

            return $services;
        } else {
            return $this->services()->where("day", $date->shortEnglishDayOfWeek)->orderBy("start")->get();
        }
    }

    public function servicePeriod(Carbon $date)
    {
        $times = collect([]);

        $services = $this->servicesByDate($date);

        if($services->count()){
            $dayStart = Carbon::parse($date->format("Y-m-d") . " " . $services->first()->start->format("H:i:s"));
            $dayFinish = Carbon::parse($date->format("Y-m-d") . " " . $services->first()->finish->format("H:i:s"));

            if($dayFinish->lessThanOrEqualTo($dayStart)){
                $dayFinish->addDay();
            }

            foreach($services as $service){
                $serviceStart = Carbon::parse($date->format("Y-m-d") . " " . $service->start->format("H:i:s"));
                $serviceFinish = Carbon::parse($date->format("Y-m-d") . " " . $service->finish->format("H:i:s"));

                if($serviceFinish->lessThanOrEqualTo($serviceStart)){
                    $serviceFinish->addDay();
                }

                if($serviceFinish->greaterThan($dayFinish)){
                    $dayFinish = $serviceFinish;
                }
            }
        }

        if($b = $this->bookings()->whereDate("booked_at", $date)->orderBy("booked_at")->first()){
            if(empty($dayStart) || $b->booked_at->lessThan($dayStart)){
                $dayStart = $b->booked_at;
            }
        }

        if($b = $this->bookings()->whereDate("booked_at", $date)->orderBy("finish_at", "DESC")->first()){
            if(empty($dayFinish) || $b->finish_at->greaterThan($dayFinish)){
                $dayFinish = $b->finish_at;
            }
        }

        if(!empty($dayStart) && !empty($dayFinish)){
            $times = CarbonPeriod::create($dayStart, CarbonInterval::minutes($this->interval), $dayFinish->subMinutes($this->interval));
        }

        return $times;
    }

app/Http/Livewire/Booking/Cancel.php
<?php

namespace App\Http\Livewire\Booking;

use App\Events\BookingStatusUpdated;
use App\Models\Booking;
use App\Notifications\Booking\StatusUpdate;
use Illuminate\Support\Facades\Notification;
use Livewire\Component;

class Cancel extends Component
{
    public $booking;
    public $confirmCancel = false;

    public function mount(Booking $booking)
    {
        $this->booking = $booking;
    }

    public function render()
    {
        return view('livewire.booking.cancel');
    }

    public function cancel()
    {
        $this->booking->status = "cancelled";
        $this->booking->save();

        BookingStatusUpdated::dispatch($this->booking);

        return redirect(route("bookings"));
    }
}

app/Http/Livewire/Booking/Index.php
<?php

namespace App\Http\Livewire\Booking;

use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;

    public $bookingVar;

    public function mount($bookings)
    {
        $this->bookingVar = $bookings;
    }

    public function render()
    {
        return view('livewire.booking.index', [
            'bookings' => auth()->user()->{$this->bookingVar}()->paginate(15)
        ]);
    }
}

app/Http/Livewire/ContactForm.php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use App\Mail\ContactForm as MailContactForm;
use Livewire\Component;

class ContactForm extends Component
{
    public $name, $email, $subject, $text, $extras, $to;
    public $subjectDisabled = false;

    protected $rules = [
        "name" => 'required',
        "email" => 'required|email',
        "subject" => 'required',
        "text" => 'required',
    ];

    public function mount($subject = null, $to = "info@mytables.co.uk", $extras = [])
    {
        if(!empty($subject)){
            $this->subject = $subject;
            $this->subjectDisabled = true;
        }

        if(Auth::check()){
            $this->name = Auth::user()->name;
            $this->email = Auth::user()->email;
        }

        $this->to = $to;
        $this->extras = $extras;
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    public function render()
    {
        return view('livewire.contact-form');
    }

    public function submit()
    {
        $this->validate();

        $text = $this->text;

        if(!empty($this->extras)){
            $text = implode("\r\n", $this->extras) . "\r\n \r\n" . $text;
        }

        Mail::to($this->to)->queue(new MailContactForm($this->name, $this->email, $this->subject, $text));

        if(Mail::failures()){
            $this->emitSelf("failed");
        } else {
            $this->emitSelf("sent");
            $this->reset(['name', 'email', 'text']);
        }
    }
}

app/Http/Livewire/Notifications/Panel.php
<?php

namespace App\Http\Livewire\Notifications;

use Illuminate\Support\Facades\Auth;
use Livewire\Component;
use Livewire\WithPagination;

class Panel extends Component
{
    use WithPagination;

    public $count;
    public $showNotifications = false;

    protected $listeners = ['showNotifications' => 'openNotifications', 'updateCount' => 'updateCount'];

    public function render()
    {
        $this->count = Auth::user()->unreadNotifications->count();

        return view('livewire.notifications.panel', [
            'notifications' => Auth::user()->notifications()->simplePaginate(15)
        ]);
    }

    public function openNotifications()
    {
        $this->showNotifications = true;
    }

    public function followNotification($id)
    {
        $notification = Auth::user()->notifications()->find($id);

        if(!$notification){
            return false;
        }

        $notification->markAsRead();

        return redirect()->to($notification->data['link']);
    }

    public function markAllRead()
    {
        Auth::user()->unreadNotifications->markAsRead();

        $this->emit("updateCount");
    }

    public function updateCount()
    {
        $this->count = Auth::user()->unreadNotifications->count();
    }
}

app/Http/Livewire/Restaurant/Nearby.php
<?php

namespace App\Http\Livewire\Restaurant;

use App\Http\Controllers\SearchController;
use Livewire\Component;

class Nearby extends Component
{
    public $restaurants = [];
    public $limit = 6;

    public function render()
    {
        return view('livewire.restaurant.nearby');
    }

    public function showMore()
    {
        $this->limit += 6;
    }

    public function load($lat, $lng)
    {
        $this->restaurants = SearchController::byRadius($lat, $lng)
            ->orderBy("distance")
            ->limit(6)
            ->get();
    }
}

app/Http/Livewire/Restaurant/Orders.php
<?php

namespace App\Http\Livewire\Restaurant;

use App\Models\Restaurant;
use Livewire\Component;
use Mockery\Exception;
use Stripe\Account;
use Stripe\AccountLink;
use Stripe\Exception\ApiErrorException;
use Stripe\Stripe;

class Orders extends Component
{
    public function render()
    {
        return view('livewire.restaurant.orders');
    }
}

resources/views/livewire/contact-form.blade.php
<form wire:submit.prevent="submit" class="space-y-5">
    <div>
        <label class="text-gray-500">Name</label>
        <x-jet-input class="w-full" wire:model="name"/>
        @error("name")<span class="text-red-600">{{ $message }}</span>@enderror
    </div>
    <div>
        <label class="text-gray-500">Email</label>
        <x-jet-input type="email" class="w-full" wire:model="email"/>
        @error("email")<span class="text-red-600">{{ $message }}</span>@enderror
    </div>
    <div>
        <label class="text-gray-500">Subject</label>
        <x-select wire:model="subject" required class="w-full" :disabled="$subjectDisabled">
            @if(empty($subject))
                <option>- Please Select -</option>
            @endif
            <option>Booking Enquiry</option>
        </x-select>
        @error("subject")<span class="text-red-600">{{ $message }}</span>@enderror
    </div>
    <div>
        <label class="text-gray-500">Your Message</label>
        <x-jet-input textarea wire:model="text" class="w-full" rows="5"/>
        @error("text")<span class="text-red-600">{{ $message }}</span>@enderror
    </div>
    <div class="text-center">
        <x-jet-button wire:loading.attr="disabled">Send</x-jet-button>
        <x-jet-action-message class="text-green-500" on="sent">Mail Sent Successfully.</x-jet-action-message>
        <x-jet-action-message class="text-red-600" on="failed">Mail Failed to Send.</x-jet-action-message>
    </div>
</form>

resources/views/livewire/dashboard.blade.php
<div class="space-y-10">
    <div>
        <x-select wire:model="rid">
            @foreach($restaurants as $r)
                <option value="{{ $r->id }}">{{ $r }}</option>
            @endforeach
        </x-select>
    </div>

    <div>
        <h2 class="font-bold text-3xl">Billing</h2>
        <div class="grid grid-flow-row lg:grid-flow-col lg:auto-cols-fr gap-6 p-6 border border-gray-100 shadow rounded">
            <div class="flex flex-col items-center justify-center px-6 text-center">
                <p class="text-6xl">&pound;{{ $restaurant->monthly_payment }}</p>
                <p>Your typical monthly payment</p>
                <p class="text-gray-600 text-sm mt-3">
                    This is calculated based on the number of bookable tables in your restaurant multiplied by your
                    monthly rate of &pound;{{ $restaurant->rate }} per table.
                </p>
            </div>
            <div class="flex flex-col items-center justify-center px-6 text-center lg:border-l lg:border-r">
                <p class="text-5xl">{{ $restaurant->next_billing_date->toFormattedDateString() }}</p>
                <p>Next payment date</p>
                <p class="text-gray-600 text-sm mt-3">
                    The date of your next payment is driven by the date you set in your billing settings.
                </p>
            </div>
            <div class="flex flex-col items-center justify-center px-6 text-center">
                <p class="text-6xl">&pound;{{ $restaurant->next_payment_amount }}</p>
                <p>Next payment amount (expected)</p>
                <p class="text-gray-600 text-sm mt-3">
                    This is calculated based on the costs you have already accrued, plus the number of bookable tables
                    you have at this moment in time multiplied by the number of days left until your next payment date.
                </p>
            </div>
            @if($balance = $restaurant->asStripeCustomer()->balance)
                <div class="flex flex-col items-center justify-center px-6 text-center lg:border-l">
                    <p class="text-6xl">{{ $balance < 0 ? "-" : "" }}&pound;{{ number_format(abs($balance)/100, 2) }}</p>
                    <p>Account Balance</p>
                    <p class="text-gray-600 text-sm mt-3">
                        @if($balance < 0)
                            A credit will be applied to your next invoice.
                        @else
                            A debit will be applied to your next invoice.
                        @endif
                    </p>
                </div>
            @endif
        </div>
    </div>

    <div>
        <h2 class="font-bold text-3xl">Bookings</h2>
        <div id="bookings_chart" class="w-full h-75"></div>
        <div id="covers_chart" class="w-full h-75"></div>
    </div>

    <div>
        <h2 class="font-bold text-3xl">Reviews</h2>
        <div id="reviews_chart" class="w-full h-75"></div>
    </div>

    @push("scripts")
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script>
            document.addEventListener('livewire:load', () => {
                google.charts.load('current', {'packages':['corechart']})
                google.charts.setOnLoadCallback(drawChart)

                function drawChart() {
                    let data = google.visualization.arrayToDataTable(@this.bookings)

                    let options = {
                        title: 'Booking Comparison vs. Next/Last Week',
                        curveType: 'function',
                        legend: { position: 'bottom' },
                        vAxis: {viewWindowMode: "explicit", viewWindow:{min:0}},
                    }

                    let chart = new google.visualization.LineChart(document.getElementById('bookings_chart'))

                    chart.draw(data, options)

                    let coversData = google.visualization.arrayToDataTable(@this.covers)

                    let coversOptions = {
                        title: 'Guests Comparison vs. Next/Last Week',
                        curveType: 'function',
                        legend: { position: 'bottom' },
                        vAxis: {viewWindowMode: "explicit", viewWindow:{min:0}},
                    }

                    let coversChart = new google.visualization.LineChart(document.getElementById('covers_chart'))

                    coversChart.draw(coversData, coversOptions);

                    let reviewsData = google.visualization.arrayToDataTable(@this.reviews)

                    let reviewsOptions = {
                        title: 'Monthly Reviews',
                        legend: { position: 'bottom' },
                        seriesType: 'line',
                        series: {0: {type: 'bars'}},
                        vAxis: {viewWindowMode: "explicit", viewWindow:{min:0}},
                        chartArea: {
                            top: 55,
                            height: '40%'
                        }
                    }

                    let reviewsChart = new google.visualization.ComboChart(document.getElementById('reviews_chart'))

                    reviewsChart.draw(reviewsData, reviewsOptions)
                }

                document.addEventListener("updated-restaurant", drawChart)
            })
        </script>
    @endpush
</div>